# temperature conversion subphase --->
FAHRENHEIT_TO_CELSIUS = "FAHRENHEIT_TO_CELSIUS"
CELSIUS_TO_FAHRENHEIT = "CELSIUS_TO_FAHRENHEIT"

# units of weight conversion subphase --->
OUNCE_TO_GRAM = "OUNCE_TO_GRAM"
GRAM_TO_OUNCE = "GRAM_TO_OUNCE"
POUND_TO_KILOGRAM = "POUND_TO_KILOGRAM"
KILOGRAM_TO_POUND = "KILOGRAM_TO_POUND"
POUND_TO_OUNCE = "POUND_TO_OUNCE"
OUNCE_TO_POUND = "OUNCE_TO_POUND"
KILOGRAM_TO_GRAM = "KILOGRAM_TO_GRAM"
GRAM_TO_KILOGRAM = "GRAM_TO_KILOGRAM"
METRIC_TON_TO_KILOGRAM = "METRIC_TON_TO_KILOGRAM"
KILOGRAM_TO_METRIC_TON = "KILOGRAM_TO_METRIC_TON"

# liquid conversion subphase --->
LITERS_TO_MILLILITERS = "LITERS_TO_MILLILITERS"
MILLILITERS_TO_LITERS = "MILLILITERS_TO_LITERS"
GALLONS_TO_LITERS = "GALLONS_TO_LITERS"
LITERS_TO_GALLONS = "LITERS_TO_GALLONS"
FLUID_OUNCES_TO_MILLILITERS = "FLUID_OUNCES_TO_MILLILITERS"
MILLILITERS_TO_FLUID_OUNCES = "MILLILITERS_TO_FLUID_OUNCES"
CUBIC_METERS_TO_LITERS = "CUBIC_METERS_TO_LITERS"
LITERS_TO_CUBIC_METERS = "LITERS_TO_CUBIC_METERS"
BARRELS_TO_CUBIC_METERS = "BARRELS_TO_CUBIC_METERS"
CUBIC_METERS_TO_BARRELS = "CUBIC_METERS_TO_BARRELS"

# dimension conversion subphase --->
METERS_TO_FEET = "METERS_TO_FEET"
FEET_TO_METERS = "FEET_TO_METERS"
METERS_TO_INCHES = "METERS_TO_INCHES"
INCHES_TO_METERS = "INCHES_TO_METERS"
CENTIMETERS_TO_INCHES = "CENTIMETERS_TO_INCHES"
INCHES_TO_CENTIMETERS = "INCHES_TO_CENTIMETERS"
KILOMETERS_TO_MILES = "KILOMETERS_TO_MILES"
MILES_TO_KILOMETERS = "MILES_TO_KILOMETERS"
METERS_TO_YARDS = "METERS_TO_YARDS"
YARDS_TO_METERS = "YARDS_TO_METERS"

# speed units conversions subphase --->
KILOMETERS_PER_HOUR_TO_METERS_PER_SECOND = "KILOMETERS_PER_HOUR_TO_METERS_PER_SECOND"
METERS_PER_SECOND_TO_KILOMETERS_PER_HOUR = "METERS_PER_SECOND_TO_KILOMETERS_PER_HOUR"
KILOMETERS_PER_HOUR_TO_MILES_PER_HOUR = "KILOMETERS_PER_HOUR_TO_MILES_PER_HOUR"
MILES_PER_HOUR_TO_KILOMETERS_PER_HOUR = "MILES_PER_HOUR_TO_KILOMETERS_PER_HOUR"
KILOMETERS_PER_HOUR_TO_KNOTS = "KILOMETERS_PER_HOUR_TO_KNOTS"
KNOTS_TO_KILOMETERS_PER_HOUR = "KNOTS_TO_KILOMETERS_PER_HOUR"


# I did not use this in the program --->
# area conversion subphase --->
# SQUARE_METER = "SQUARE_METER"
# SQUARE_FOOT = "SQUARE_FOOT"
# SQUARE_KILOMETER = "SQUARE_KILOMETER"
# SQUARE_MILE = "SQUARE_MILE"
# HECTARE = "HECTARE"
# ACRE = "ACRE"
# SQUARE_YARDS = "SQUARE_YARDS"

# I did not use this in the program --->
# memory units and their conversions subphase --->
# BIT = "BIT"
# BYTE = "BYTE"
# KILOBYTE = "KILOBYTE"
# MEGABYTE = "MEGABYTE"
# GIGABYTE = "GIGABYTE"
# TERABYTE = "TERABYTE"
# PETABYTE = "PETABYTE"
# EXABYTE = "EXABYTE"
# ZETTABYTE = "ZETTABYTE"
# YOTTABYTE = "YOTTABYTE"
